language: bash
os: linux
sudo: enabled
env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8

install:
  - sudo apt update
  - sudo apt install -y snapd
  - sudo snap install lxd --channel 3.0/stable
  - sudo snap install snapcraft --candidate --classic
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - mkdir -p "$TRAVIS_BUILD_DIR/snaps-cache"
matrix:
  include:
    - name: "Eclipse Java"
      env: VARIANT=java
    - name: "Eclipse CDT"
      env: VARIANT=cdt
script:
  - export PATH=/snap/bin:$PATH
  - cd eclipse-$VARIANT && sudo snapcraft cleanbuild
  - sudo cp eclipse-$VARIANT/*.snap "$(echo "$TRAVIS_REPO_SLUG" | sed -e 's|.*/\(.*\)|\1|')-pr$TRAVIS_PULL_REQUEST.snap"
after_success:
  - sudo snap install transfer
  - timeout 180 sudo /snap/bin/transfer "$(echo "$TRAVIS_REPO_SLUG" | sed -e 's|.*/\(.*\)|\1|')-pr$TRAVIS_PULL_REQUEST.snap"
after_failure:
  - sudo journalctl -u snapd
  - sudo snap install http
  - /snap/bin/http https://api.snapcraft.io/v2/snaps/info/core architecture==amd64 Snap-Device-Series:16
