#!/bin/bash
EXTRA_ARGS=()
if [ -f "$SNAP_USER_DATA/eclipse.ini" ]; then
    # Allow the user to override the eclipse.ini with their own version
    EXTRA_ARGS+=("--launcher.ini" "$SNAP_USER_DATA/eclipse.ini")
else
    echo "To override eclipse.ini, copy the default file to '$SNAP_USER_DATA/eclipse.ini' and modify to suit."
fi

ECLIPSE_WORKSPACE=$SNAP_USER_DATA/workspace
mkdir -p $ECLIPSE_WORKSPACE
echo Using workspace at $ECLIPSE_WORKSPACE.

exec "$SNAP/eclipse" -configuration "${SNAP_USER_DATA}/${SNAP_ARCH}/configuration" -data "$ECLIPSE_WORKSPACE" "${EXTRA_ARGS[@]}" "$@"
