name: eclipse
base: core22

version: '2023-09'
summary: Extensible Tool Platform and Java IDE
description:
  Eclipse provides IDEs and platforms for nearly every language and architecture.
  We are famous for our Java IDE, C/C++, JavaScript and PHP IDEs built on extensible
  platforms for creating desktop, Web and cloud IDEs. These platforms deliver the most
  extensive collection of add-on tools available for software developers.

grade: devel
confinement: strict

architectures:
  - build-on: amd64

slots:
  eclipse:
    interface: dbus
    bus: session
    name: org.eclipse.Eclipse

apps:
  eclipse:
    command: bin/eclipse-wrapper
    extensions: [gnome]
    desktop: eclipse.desktop
    plugs: [eclipse-workspace]

# mkdir ~/workspace
# snap connect eclipse:eclipse-workspace
plugs:
  eclipse-workspace:
    interface: personal-files
    write:
    - $HOME/workspace
    

parts:
  eclipse:
    plugin: dump
    source: https://download.eclipse.org/technology/epp/downloads/release/2023-09/R/eclipse-java-2023-09-R-linux-gtk-x86_64.tar.gz
    source-checksum: "sha512/eb2c72dbc545d3e828430c359e6c76ca9f4184095504bec7b0ce675fffea74cb558aa307227fb533993f703fbcafaab6ca2daec3200a0987a96ca9cf8dbcee01"
    build-attributes:
      - no-patchelf
    override-build: |
      snapcraftctl build
      chmod +x $SNAPCRAFT_PART_INSTALL/eclipse
      chmod +x $SNAPCRAFT_PART_INSTALL/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.8.v20230831-1047/jre/bin/java
  wrappers:
    plugin: dump
    source: snap/local/wrappers
    organize:
      eclipse: bin/eclipse-wrapper
  eclipse_desktop:
    plugin: dump
    source: snap/gui
