name: eclipse
version: '2018-12'
summary: Extensible Tool Platform and Java IDE
description:
  Eclipse provides IDEs and platforms for nearly every language and architecture.
  We are famous for our Java IDE, C/C++, JavaScript and PHP IDEs built on extensible
  platforms for creating desktop, Web and cloud IDEs. These platforms deliver the most
  extensive collection of add-on tools available for software developers.

grade: stable
confinement: classic

architectures:
  - build-on: amd64

apps:
  eclipse:
    command: eclipse
    desktop: eclipse.desktop

parts:
  gnome:
    plugin: nil
    build-packages:
      - software-properties-common
    override-pull: |
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt -y update
      apt -y upgrade
  desktop:
    after: [eclipse]
    plugin: dump
    source: .
    prime:
      - eclipse.desktop

  eclipse:
    after: [gnome]
    plugin: dump
    source:
      - on amd64: http://ftp.halifax.rwth-aachen.de/eclipse/technology/epp/downloads/release/$SNAPCRAFT_PROJECT_VERSION/R/eclipse-java-$SNAPCRAFT_PROJECT_VERSION-R-linux-gtk-x86_64.tar.gz
    build-attributes:
      - no-patchelf
