name: eclipse
base: core22

version: 2024-03
summary: Extensible Tool Platform and Java IDE
website: https://eclipse.org/ide
description:
  Eclipse provides IDEs and platforms for nearly every language and architecture.
  We are famous for our Java IDE, C/C++, JavaScript and PHP IDEs built on extensible
  platforms for creating desktop, Web and cloud IDEs. These platforms deliver the most
  extensive collection of add-on tools available for software developers.

grade: stable
confinement: classic

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  eclipse:
    command: bin/eclipse-wrapper
    environment:
      __NV_PRIME_RENDER_OFFLOAD: 1

parts:
  eclipse:
    plugin: dump
    source:
      - on amd64: "https://download.eclipse.org/technology/epp/downloads/release/$SNAPCRAFT_PROJECT_VERSION/R/eclipse-java-$SNAPCRAFT_PROJECT_VERSION-R-linux-gtk-x86_64.tar.gz"
      - on arm64: "https://download.eclipse.org/technology/epp/downloads/release/$SNAPCRAFT_PROJECT_VERSION/R/eclipse-java-$SNAPCRAFT_PROJECT_VERSION-R-linux-gtk-aarch64.tar.gz"
    build-attributes:
      - no-patchelf
    stage-packages:
      - libffi7
      - libfreetype6
      - libpng16-16
      - libgdk-pixbuf2.0-0
      - libsecret-1-0
      - libasound2
      - libxi6
      - libxrender1
      - libxtst6
  wrappers:
    plugin: dump
    source: snap/local/wrappers
    organize:
      eclipse: bin/eclipse-wrapper
