name: eclipse
base: core20

version: '2022-06'
summary: Extensible Tool Platform and Java IDE
description:
  Eclipse provides IDEs and platforms for nearly every language and architecture.
  We are famous for our Java IDE, C/C++, JavaScript and PHP IDEs built on extensible
  platforms for creating desktop, Web and cloud IDEs. These platforms deliver the most
  extensive collection of add-on tools available for software developers.

grade: stable
confinement: classic

architectures:
  - build-on: amd64

apps:
  eclipse:
    command: bin/eclipse-wrapper

parts:
  eclipse:
    plugin: dump
    source: https://download.eclipse.org/technology/epp/downloads/release/2022-06/R/eclipse-java-2022-06-R-linux-gtk-x86_64.tar.gz
    source-checksum: "sha512/69c7bece9cf9b632c0f3d8072f206b8e574a53bfa46fce6e257e32e0841d564aec92b03eb82bf4cfd97307fa9b82b1f9d5914ddb1cf4e33d6714b25dd3d59a70"
    build-attributes:
      - no-patchelf
    stage-packages:
      - libffi7
      - libfreetype6
      - libpng16-16
      - libgdk-pixbuf2.0-0
      - libsecret-1-0
      - libasound2
      - libxi6
      - libxrender1
      - libxtst6
  wrappers:
    plugin: dump
    source: snap/local/wrappers
    organize:
      eclipse: bin/eclipse-wrapper
